<?php

return [
    'cache'   => false,
    'main'    => '/_dist/js/require/main.js',
    'default' => [
        "moment",
        "datetimepicker",
        "globalize",
        "select2",
        "list",
        "iCheck",
        "tinycon",
        "context_menu_datatables",
        "qtip",
        "yii_active_forms",
        "jquery-validation",
        "lodash",
        "gridstack",
        "mouse_wheel",
        "matchHeight",
        "hammerjs",
        "jquery-hammerjs",
        "perfect-scrollbar.jquery",
        "perfect-scrollbar",
        "enquire",
        "moment",
        "jquery-hoverintent",
        "noty",
        "menu_aim",
        "pace",
        "slick",
        "swal",
        "jquery-minicolors",
        "datatables-helpers",
        "flash-messenger",
        "/packages/core/js/on-load.js",
        "filters",
        'childs' => [
            "app_material",
            "app_forms",
            "app_menu",
            "app_dropdowns",
            "app_mechanics",
            "datatables.net",
            "datatables-responsive",
            "datatables-scroller",
            "context_menu",
        ]
    ]
];
