engines:
  duplication:
    enabled: true
    config:
      languages:
      - html
      - twig
      - php
  eslint:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "codesize,design,unusedcode,resources/codeclimate/phpmd_ruleset.xml"
ratings:
  paths:
  - "**.php"
exclude_paths:
- bootstrap/
- build/
- builds/
- public/
- storage/
- src/
- resources/codeclimate/
- resources/laravolt/
- resources/messages/
- resources/themes/
